### ISSUE TITLE
Strap failing :( not quite sure what the issue is

### ISSUE THREAD

**Issue by jpoleary** [umts/strap#1]
```
AF-PVTA28:~ jpoleary-af (deluded)$bash ~/Downloads/strap.sh --debug
+ STDIN_FILE_DESCRIPTOR=0
+ '[' -t 0 ']'
+ STRAP_INTERACTIVE=1
+ STRAP_GIT_EMAIL=jpoleary@umass.edu
+ STRAP_GITHUB_USER=jpoleary
+ STRAP_GITHUB_TOKEN=0f45f39020cdb862fc0b9686703a893481f6fa55
+ STRAP_ISSUES_URL=https://github.com/umts/strap/issues/new
+ sudo -k
+ su jpoleary-d -c '/usr/bin/sudo -k'
Password:
++ sw_vers -productVersion
+ MACOS_VERSION=10.15.4
+ echo 10.15.4
+ grep -E '^10.(9|10|11|12|13|14)'
+ abort 'Run Strap on macOS 10.9/10/11/12/13/14.'
+ STRAP_STEP=
+ echo '!!! Run Strap on macOS 10.9/10/11/12/13/14.'
!!! Run Strap on macOS 10.9/10/11/12/13/14.
+ exit 1
+ cleanup
+ set +e
+ '[' -n '' ']'
+ sudo -k
+ su jpoleary-d -c '/usr/bin/sudo -k'
Password:
+ rm -f ''
+ '[' -z '' ']'
+ '[' -n '' ']'
+ echo '!!! FAILED'
!!! FAILED
+ '[' -z 1 ']'
```

**Comment by Anbranin** [comment]
We discovered that we really should completely erase laptops before giving them to new developers. Turns out XCode was out of date, which we only discovered after Googling an error message given by ruby-build that threw when we tried `brew install rbenv`, having given up trying to use the strap script. Then we discovered that a previous developer's *cough*@jforgue*cough* Apple ID was tied to all the apps, making it impossible to update them for @jpoleary. Solution was to uninstall & reinstall, which is taking a while.

**Comment by werebus** [comment]
So, all that is _a_ problem, but the actual problem here is that the script hasn't been updated to include 10.15 as a valid version of MacOS.

**Comment by werebus** [comment]
(On our fork)

**Comment by Anbranin** [comment]
Ya
