### ISSUE TITLE
Add *user* to the admin group

### ISSUE THREAD

**Issue by dirschn** [umts/strap#5]
Running the script from my normal non-elevated account I get 
`!!! Add *USER* to the admin group.
Password:
*USER* is not in the sudoers file.  This incident will be reported.
!!! FAILED
!!! Run 'strap.sh --debug' for debugging output.
!!! If you're stuck: file an issue with debugging output at:
!!!   https://github.com/umts/strap/issues/new` 

I'm guessing adding my non-elevated account to the sudoers file is not what we want to do?

**Comment by werebus** [comment]
I have yet to find a non-heinous way to get Strap, rbenv, and Homebrew to all deal with a non-admin user who is you, and also an admin-user who is not "you". You need to be an admin to make a number of the changes that Strap does, but it your admin account installs Homebrew, then your non-admin account can't run it.

If you install rbenv using your admin account because you need it to run Homebrew, then you'll end up with files in your home directory not owned by you (rather owned by your admin accout).

It's a disaster all the way down. Homebrew really operates under the assumption that your laptop has one user and that user is an admin. It's difficult to convince it otherwise. For a while I experimented with a project [to get Strap to run as your non-admin user](https://github.com/umts/strap-lie). But Strap added some additional sudo cleverness that was incompatible.

I think it's _possible_ to get it to work, but it's been a pretty tough nut and I don't have a lot of bandwidth for it at the moment. For now, I will make the following statements:

* You _have_ access to an admin account that can modify other accounts on your computer in System Preferences
* Whether any _particular_ account is a local admin isn't enforced anywhere
* If your `-af` account were somehow an admin, everything would work fine...

**Comment by dirschn** [comment]
Well, I rebooted today and somehow my `-af` account suddenly had admin priveleges, and now it seems to work. Technology sure can be weird sometimes...
